### ISSUE TITLE
life regenerating much slower than vanilla

### ISSUE THREAD

**Issue by benyben27** [nxPublic/ValheimPlus#37]
we play in a group of 4 and only 2 have experienced this problem 
all using the same config file
https://pastebin.com/RecnxEVt

**Comment by nxPublic** [comment]
Issue is resolved in 0.8 that is released tomorrow.

**Comment by benyben27** [comment]
never mind my friends were just stupid
made them to compare it to vanilla and its still the same

**Comment by benyben27** [comment]
wait there is an issue?

**Comment by nxPublic** [comment]
There was a issue related to receiving health regeneration, yes.
